### PR TITLE
Create Parameter save file

### PR DESCRIPTION
**Pull request by darkdir**

### CODE REVIEW

**Comment by Ming2k8-Coder** [comment]
Hey, thanks for contribution but main file is votol coms protocol

**Comment by Ming2k8-Coder** [comment]
Hey, did you have the wechat program, or can you get the votol firmware from that

**Comment by darkdir** [comment]
Hey
I simply used the Votol PC application:
-copy original configuration
-change a value
-save to new file
-compare the difference (NotePad++ with plugin)
-repeat one by one

some byte remains invisible on the application so I don't know exactly what
it is

This APP [image: Screenshot_2024-10-27-16-12-11-333_com.tencent.mm.jpg]
[image: Screenshot_2024-10-28-17-49-06-567_com.tencent.mm~2.jpg]
I think the missing bytes are in blue
and in red TC1/2/3

Le lun. 28 oct. 2024 à 10:49, Ming2k8-Coder ***@***.***> a
écrit :

**Comment by Ming2k8-Coder** [comment]
I have decoded all, you can see in parameter save file (nearly same coms protocol)

**Pull request merged**
